version: "3"
services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    image: jupyter/minimal-notebook
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ..:/workspace:cached
      - ../work:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''
    